# Generated by Django 3.0.6 on 2020-06-04 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneModel',
        ),
    ]
