# Generated by Django 3.0.6 on 2020-06-04 05:22

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_delete_phonemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', phone_field.models.PhoneField(blank=True, help_text='Enter phone number', max_length=31)),
            ],
        ),
    ]
