# Generated by Django 3.0.6 on 2020-06-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_phonemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='body',
            field=models.CharField(default='hi', max_length=10000),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='media_url',
            field=models.CharField(default='hi', max_length=1000),
        ),
    ]
