# Generated by Django 3.0.6 on 2020-06-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200604_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='to',
            field=models.CharField(blank=True, help_text='Enter phone number', max_length=12),
        ),
    ]
