# Generated by Django 3.0.6 on 2020-06-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200604_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Enter Verification Code', max_length=12)),
            ],
        ),
    ]
