# Generated by Django 3.0.6 on 2020-06-04 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_verifymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifymodel',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code', to='pages.PhoneModel', unique=None),
        ),
    ]
