# Generated by Django 3.0.6 on 2020-06-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_verifymodel_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='to',
            field=models.CharField(help_text='Enter phone number', max_length=12, unique=True),
        ),
    ]
