# Generated by Django 3.0.6 on 2020-06-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200604_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='to',
            field=models.CharField(help_text='Enter phone number', max_length=12),
        ),
    ]
