# Generated by Django 3.0.6 on 2020-06-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20200604_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='sid',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
